<div class="container">
    <?php if (isset($this->auth_info) && ($this->auth_info->type == "root" || $this->auth_info->type == "admin")) { ?>
        <?php if ($this->checkAvailabiliy) { ?>
            <button class="btn btn-danger closeSystem" style="position: fixed;right: 0px;top: 0px;"><span class='glyphicon glyphicon-remove-circle'>Close The System</span></button>
        <?php } else { ?>
            <button class="btn btn-success closeSystem" style="position: fixed;right: 0px;top: 0px;"><span class='glyphicon glyphicon-ok'>Open The System</span></button>
            <?php
        }
    }
    ?>
    <!--        <div class="panel-group ">
                <div class="panel panel-default panel-info">
                    <div class="panel-heading">
                        <a style="float: left;" data-toggle="collapse"    class="btn btn-type btn-sm btn-default collapsed" href="#collapse1"></a>
                        <div style="text-align: center;" class="panel-title">
                            <a href="#"  class="text-center ">Table name</a> 
                        </div>
                    </div>
                    <div  id="collapse1" class="panel-collapse collapse">
        
                        <table>
                            <thead>
                                <tr>
                                    <th>Option</th>
                                    <th>Default</th>
                                    <th>Description</th>
        
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><strong><a href="#"  >howSpeed</a></strong></td>
                                    <td>15</td>
                                    <td>The speed of the show/reveal</td>
                                </tr>
                                <tr>
                                    <td><a href="#"><strong>showEasing</strong></a></td>
                                    <td>'linear'</td>
                                    <td>The easing of the show/reveal</td>
                                </tr>
        
        
                            </tbody>
                        </table>
        
                    </div>
                </div>
            </div>-->

    <?php if (isset($this->auth_info) && $this->auth_info->type != "user") { ?>
        <button class='btn btn-success' data-toggle='modal' data-target='#addCatModal'><span class="glyphicon glyphicon-plus"></span> Add Category</button>
    <?php } ?>

    <div class='modal fade' id='addCatModal'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-heading'>
                    <div class='modal-title'>
                        <h2 class='bg-primary'>Add Category</h2>
                    </div>
                </div>
                <div class='modal-body'>
                    <form role="form" id="addCatForm">
                        <div class="form-group has-success">
                            <label for="text">Category:  </label>
                            <?= $this->addCatForm->category->renderViewHelper(); ?>
                            <span class="errorMsg" id="categoryError"></span>
                        </div>

                        <div class='modal-footer'>
                            <?= $this->addCatForm->submit->renderViewHelper(); ?>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class='modal fade' id='editCatModal'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-heading'>
                    <div class='modal-title'>
                        <h2 class='bg-primary'>Edit Category</h2>
                    </div>
                </div>
                <div class='modal-body'>
                    <form role="form" id="editCatForm">
                        <div class="form-group has-success">
                            <label for="text">Category:  </label>
                            <input type="text" id="e_category" name="category" class="form-control" required/>
                            <span class="errorMsg" id="e_categoryError"></span>
                        </div>


                        <input type="hidden" id="editID" name="editID">
                        <div class='modal-footer'>
                            <button id="editCat" type="submit" class="btn btn-info">Edit Category</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class='modal fade' id='addForumModal'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-heading'>
                    <div class='modal-title'>
                        <h2 class='bg-primary'>Add Forum</h2>
                    </div>
                </div>
                <div class='modal-body'>
                    <form role="form" id="addForumForm">
                        <div class="form-group has-success">
                            <label for="text">Forum:  </label>
                            <?= $this->addForumForm->name->renderViewHelper(); ?>
                            <span class="errorMsg" id="nameError"></span>
                        </div>
                        <input type="hidden" id="catId" name="category_id">
                        <div class='modal-footer'>
                            <?= $this->addForumForm->submit->renderViewHelper(); ?>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class='modal fade' id='editForumModal'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-heading'>
                    <div class='modal-title'>
                        <h2 class='bg-primary'>Edit Forum</h2>
                    </div>
                </div>
                <div class='modal-body'>
                    <form role="form" id="editForumForm">
                        <div class="form-group has-success">
                            <label for="text">Forum:  </label>
                            <input type="text" id="e_name" name="name" class="form-control" required/>
                            <span class="errorMsg" id="e_nameError"></span>
                        </div>

                        <input type="hidden" id="e_catID" name="category_id">
                        <input type="hidden" id="f_editID" name="f_editID">
                        <div class='modal-footer'>
                            <button id="editForum" type="submit" class="btn btn-info">Edit Forum</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <?php
    if (!empty($this->index)) {

        for ($i = 0; $i < count($this->index); $i++) {

            $cat_name = $this->index[$i]['category'];
            $forum_name = $this->index[$i]['name'];
            $cat_id = $this->index[$i]['id'];
            $forum_id = $this->index[$i]['forum_id'];
            ?>              
            <div class='panel-group' id="<?= $cat_id ?>">
                <div class='panel panel-default panel-info'>
                    <div class='panel-heading'>
                        <a style='float: left;' data-toggle='collapse'    class='btn  btn-type btn-sm btn-default collapsed' href='#collapse<?= $i ?>'></a>
                        <?php if (isset($this->auth_info) && $this->auth_info->type != "user") { ?>
                            <button style="float: right;height: 30px;line-height: 40px;border-radius: 18px;padding: 0 13px 1px 7px;" class='btn btn-success addForumBtn' data-toggle='modal' data-target='#addForumModal'><span class="glyphicon glyphicon-plus"></span> Add Forum</button>
                            <button style="float: right;height: 30px;line-height: 40px;border-radius: 18px;padding: 0 13px 1px 7px;" class='btn btn-danger deleteCat'><span class="glyphicon glyphicon-remove-circle"></span>Delete</button>
                            <button style="float: right;height: 30px;line-height: 40px;border-radius: 18px;padding: 0 13px 1px 7px;" class='btn btn-info fillEditCat' data-toggle='modal' data-target='#editCatModal'><span class="glyphicon glyphicon-pencil"></span>Edit</button>
                        <?php } ?>
                        <div style='text-align: center;' class='panel-title'>
                            <a href='#' class='text-center '><?= $cat_name ?></a> 


                        </div>
                    </div>
                    <div  id='collapse<?= $i ?>' class='panel-collapse collapse'>
                        <table>
                            <thead>
                                <tr>
                                    <th>name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <?php if (isset($forum_name)) { ?>
                                <tbody>
                                    <tr id="<?= $forum_id ?>">
                                        <td><strong><a href='#'  ><?= $forum_name ?></a></strong></td>
                                        <td>
                                            <?php if (isset($this->auth_info) && $this->auth_info->type != "user") { ?>
                                                <button style="float: right;height: 30px;line-height: 40px;border-radius: 18px;padding: 0 13px 1px 7px;" class='btn btn-danger deleteForum'><span class="glyphicon glyphicon-remove-circle"></span>Delete</button>
                                                <button style="float: right;height: 30px;line-height: 40px;border-radius: 18px;padding: 0 13px 1px 7px;" class='btn btn-info fillEditForum' data-toggle='modal' data-target='#editForumModal'><span class="glyphicon glyphicon-pencil"></span>Edit</button>
                                            <?php } ?>    
                                        </td>
                                    </tr>
                                    <?php
                                    for ($v = $i + 1; $v < count($this->index); $v++) {
                                        if ($this->index[$v]['id'] == $cat_id) {
                                            $forum_name = $this->index[$v]['name'];
                                            $forum_id = $this->index[$v]['forum_id'];
                                            ?>    
                                            <tr id="<?= $forum_id ?>">
                                                <td><strong><a href='#'  ><?= $forum_name ?></a></strong></td>
                                                <td>
                                                    <?php if (isset($this->auth_info) && $this->auth_info->type != "user") { ?>
                                                        <button style="float: right;height: 30px;line-height: 40px;border-radius: 18px;padding: 0 13px 1px 7px;" class='btn btn-danger deleteForum'><span class="glyphicon glyphicon-remove-circle"></span>Delete</button>
                                                        <button style="float: right;height: 30px;line-height: 40px;border-radius: 18px;padding: 0 13px 1px 7px;" class='btn btn-info fillEditForum' data-toggle='modal' data-target='#editForumModal'><span class="glyphicon glyphicon-pencil"></span>Edit</button>
                                                    <?php } ?>
                                                </td>
                                            </tr>

                                            <?php
                                            $i++;

                                            continue;
                                        } else {
                                            break;
                                        }
                                    }
                                    ?>                    
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>
                </div> 
            </div>
            <?php
        }
    }
    ?>
</div>
<script>
    $(document).ready(function () {
        $(document).on("click", ".closeSystem", function () {
            var btn = $(this);
            if ($(this).text() == "Open The System") {
                var available = 1;
            } else if ($(this).text() == "Close The System") {
                var available = 0;
            } else {
                alert("Error in value, Try again");
            }
            if (typeof available !== 'undefined') {
                var obj = {
                    available: available
                }
                $.ajax({
                    url: "<?= $this->baseUrl() ?>/index/change-availability",
                    method: "post",
                    dataType: "json",
                    data: obj,
                    success: function (data) {
                        if (data.status == "success") {
                            if (data.available == "1") {
                                $(btn).removeClass("btn-success");
                                $(btn).addClass("btn-danger");
                                $(btn).html("<span class='glyphicon glyphicon-remove-circle'>Close The System</span>");
                            } else {
                                $(btn).removeClass("btn-danger");
                                $(btn).addClass("btn-success");
                                $(btn).html("<span class='glyphicon glyphicon-ok'>Open The System</span>");
                            }
                        } else {
                            alert("Error in Change Close");
                        }
                    },
                    error: function (errorData) {
                        alert("Error in change close process");
                    },
                });
            }
        });
        ///////////////////////Category Section////////////////////////
        $("form#addCatForm").submit(function () {
            var formData = new FormData(this);
            $(".errorMsg").html("");

            $.ajax({
                url: "<?= $this->baseUrl() ?>/category/add",
                type: 'POST',
                data: formData,
                dataType: "json",
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data.status == "success") {
                        window.location.href = "index"
                    } else if (data.status == "failed") {
                        for (var key in data.errorMessages) {
                            if (!data.errorMessages.hasOwnProperty(key))
                                continue;
                            var errorMsg = data.errorMessages[key];
                            $("#" + key + "Error").html(errorMsg);
                        }
                    } else if (data.status == "error") {
                        alert("Error in  Add Category!! .. try again");
                    }
                },
                error: function (errorData) {
                    console.log(errorData);
                    alert("Error in F process");
                },
            });
            return false;
        });

        $(document).on("click", ".fillEditCat", function () {
            $(".errorMsg").html("");
            $.ajax({
                url: "<?= $this->baseUrl() ?>/category/edit",
                method: "get",
                dataType: "json",
                data: {"cat_id": $(this).parent().parent().parent().attr("id")},
                success: function (data) {
                    if (data.status == "success") {
                        $('#editCatModal #e_category').val(data.editRow.category);
                        $('#editCatModal #editID').val(data.editRow.id);
                    } else {
                        alert("Error in Edit process");
                        $('#editCatModal').modal('hide');
                    }
                },
                error: function (errorData) {
                    alert("Error in fill process");
                },
            });
        });

        $("form#editCatForm").submit(function () {
            var formData = new FormData(this);
            $(".errorMsg").html("");
            $.ajax({
                url: "<?= $this->baseUrl() ?>/category/edit",
                type: 'POST',
                data: formData,
                dataType: "json",
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data.status == "success") {
                        window.location.href = "index"
                    } else if (data.status == "failed") {
                        for (var key in data.errorMessages) {
                            if (!data.errorMessages.hasOwnProperty(key))
                                continue;
                            var errorMsg = data.errorMessages[key];
                            $("#e_" + key + "Error").html(errorMsg);
                        }
                    } else if (data.status == "error") {
                        alert("Error in  Edit Category!! .. try again");
                    }
                },
                error: function (errorData) {
                    console.log(errorData);
                    alert("Error in F process");
                },
            });
            return false;
        });

        $(document).on("click", ".deleteCat", function () {
            var catRow = $(this);
            var obj = {
                cat_id: $(this).parent().parent().parent().attr("id"),
            }
            $.ajax({
                url: "<?= $this->baseUrl() ?>/category/delete",
                method: "post",
                dataType: "json",
                data: obj,
                success: function (data) {
                    if (data.status == "success") {
                        $(catRow).parent().parent().parent().remove();
                    } else {
                        alert("Error in delete process");
                    }
                },
                error: function (errorData) {
                    console.log(errorData);
                    alert("Error in F process");
                },
            });
        });

        ///////////////////////Forum Section////////////////////////
        $(document).on("click", ".addForumBtn", function () {
            var myCatId = $(this).parent().parent().parent().attr("id");
            $("#addForumForm #catId").val(myCatId);
            $(".errorMsg").html("");
        });

        $("form#addForumForm").submit(function () {
            var formData = new FormData(this);

            $(".errorMsg").html("");

            $.ajax({
                url: "<?= $this->baseUrl() ?>/forum/add",
                type: 'POST',
                data: formData,
                dataType: "json",
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data.status == "success") {
                        window.location.href = "index"
                    } else if (data.status == "failed") {
                        for (var key in data.errorMessages) {
                            if (!data.errorMessages.hasOwnProperty(key))
                                continue;
                            var errorMsg = data.errorMessages[key];
                            $("#" + key + "Error").html(errorMsg);
                        }
                    } else if (data.status == "error") {
                        alert("Error in  Add Forum!! .. try again");
                    }
                },
                error: function (errorData) {
                    console.log(errorData);
                    alert("Error in F process");
                },
            });
            return false;
        });

        $(document).on("click", ".fillEditForum", function () {
            $(".errorMsg").html("");
            $.ajax({
                url: "<?= $this->baseUrl() ?>/forum/edit",
                method: "get",
                dataType: "json",
                data: {"forum_id": $(this).parent().parent().attr("id")},
                success: function (data) {
                    if (data.status == "success") {
                        $('#editForumModal #e_name').val(data.editRow.name);
                        $('#editForumModal #e_catId').val(data.editRow.category_id);
                        $('#editForumModal #f_editID').val(data.editRow.id);
                    } else {
                        alert("Error in Edit process");
                        $('#editCatModal').modal('hide');
                    }
                },
                error: function (errorData) {
                    alert("Error in fill process");
                },
            });
        });

        $("form#editForumForm").submit(function () {
            var formData = new FormData(this);
            $(".errorMsg").html("");
            $.ajax({
                url: "<?= $this->baseUrl() ?>/forum/edit",
                type: 'POST',
                data: formData,
                dataType: "json",
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data.status == "success") {
                        window.location.href = "index"
                    } else if (data.status == "failed") {
                        for (var key in data.errorMessages) {
                            if (!data.errorMessages.hasOwnProperty(key))
                                continue;
                            var errorMsg = data.errorMessages[key];
                            $("#e_" + key + "Error").html(errorMsg);
                        }
                    } else if (data.status == "error") {
                        alert("Error in  Edit Category!! .. try again");
                    }
                },
                error: function (errorData) {
                    console.log(errorData);
                    alert("Error in F process");
                },
            });
            return false;
        });
        
        $(document).on("click", ".deleteForum", function () {
        alert($(this).parent().parent().attr("id"));
            var forumRow = $(this);
            var obj = {
                forum_id: $(this).parent().parent().attr("id"),
            }
            $.ajax({
                url: "<?= $this->baseUrl() ?>/forum/delete",
                method: "post",
                dataType: "json",
                data: obj,
                success: function (data) {
                    if (data.status == "success") {
                        $(forumRow).parent().parent().remove();
                    } else {
                        alert("Error in delete process");
                    }
                },
                error: function (errorData) {
                    console.log(errorData);
                    alert("Error in F process");
                },
            });
        });
    });
</script>