<footer style='background: url("<?= BASE_URL ?>static/img/banner2.jpg") no-repeat;'>
    <!--<div  class="footer-section " >-->
        <div class="container">
            <!--<div class="footer-grids">-->
                <!--<div class="col-sm-6 col-md-6 col-lg-6 col-xs-6 footer-grid">-->
                <h3 style="color: #9d9d9d"><b>about us</b></h3>
                    <p>Zforum always with you ..</p> 
                    BeConnected with the world</p>
                    <p> Copyright &copy;2016  All rights  Reserved </p>

                <!--</div>-->
<!--                <div class="col-sm-3 col-md-3 col-lg-3 col-xs-3 footer-grid">
                    <h3>Opening Hours</h3>
                    <p><span>Mon-Thu:</span> 7:00am-8:00pm</p> 
                    <p><span>Fri-Sun:</span> 7:00am-4:30pm</p>

                </div>
                <div class="col-sm-3 col-md-3 col-lg-3 col-xs-3  footer-grid">
                    <h3>Our Location</h3>
                    <p>ITI-Smart Village</p>

                </div>-->
                <!--<div class="clearfix"></div>-->
            <!--</div>-->

        </div>
    <!--</div>-->

</footer>


</div>
</body>
</html>
