<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            /* Icon when the collapsible content is shown */
            .btn-type:after {
                font-family: "Glyphicons Halflings";
                content: "\e114";
                float: right;
                margin-left: 15px;
            }
            /*Icon when the collapsible content is hidden */
            .btn-type.collapsed:after {
                content: "\e080";
            }


            strong {
                font-weight: bold; 
            }

            em {
                font-style: italic; 
            }

            table {
                background: #f5f5f5;
                border-collapse: separate;
                box-shadow: inset 0 1px 0 #fff;
                font-size: 12px;
                line-height: 24px;
                margin: 30px auto;
                text-align: left;
                width: 100%;
            }	

            th {
                background:  linear-gradient(#777, #444);
                border-left: 1px solid #555;
                border-right: 1px solid #777;
                border-top: 1px solid #555;
                border-bottom: 1px solid #333;
                box-shadow: inset 0 1px 0 #999;
                color: #fff;
                font-weight: bold;
                padding: 10px 15px;
                position: relative;
                text-shadow: 0 1px 0 #000;
                font-size: medium;
            }

            th:after {
                background: linear-gradient(rgba(255,255,255,0), rgba(255,255,255,.08));
                content: '';
                display: block;
                height: 25%;
                left: 0;
                margin: 1px 0 0 0;
                position: absolute;
                top: 25%;
                width: 100%;
            }

            th:first-child {
                border-left: 1px solid #777;	
                box-shadow: inset 1px 1px 0 #999;
            }

            th:last-child {
                box-shadow: inset -1px 1px 0 #999;
            }

            td {
                border-right: 1px solid #fff;
                border-left: 1px solid #e8e8e8;
                border-top: 1px solid #fff;
                border-bottom: 1px solid #e8e8e8;
                padding: 10px 15px;
                position: relative;
                transition: all 300ms;
                font-size: medium;
                vertical-align:middle;
            }

            td:first-child {
                box-shadow: inset 1px 0 0 #fff;
            }	

            td:last-child {
                border-right: 1px solid #e8e8e8;
                box-shadow: inset -1px 0 0 #fff;
            }	


            tr:last-of-type td {
                box-shadow: inset 0 -1px 0 #fff; 
            }

            tr:last-of-type td:first-child {
                box-shadow: inset 1px -1px 0 #fff;
            }	

            tr:last-of-type td:last-child {
                box-shadow: inset -1px -1px 0 #fff;
            }	

            tbody:hover td {
                color: transparent;
                text-shadow: 0 0 3px #aaa;
            }

            tbody:hover tr:hover td {
                color: #444;
                text-shadow: 0 1px 0 #fff;
            }
        </style>
    </head>
    <body>

        <header>
            <div class="navbar-wrapper" style="margin-top: 5%;">
                <div class="container">

                    <nav class="navbar navbar-inverse navbar-static-top">
                        <div class="container">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="<?= $this->baseUrl() ?>/index"></a>
                            </div>
                            <div id="navbar" class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">&nbsp; 
                                    <li class="active"><a href="<?= $this->baseUrl() ?>/index">Home</a></li>&nbsp;

                                    <?php if (!empty($this->auth_info)) { ?>
                                        <li><a href="<?= $this->baseUrl() ?>/post">My Posts</a></li>&nbsp; 
                                        <?php if (!empty($this->auth_info->type) && $this->auth_info->type != "user") { ?>
                                            <li><a href="<?= $this->baseUrl() ?>/user">Users</a></li>&nbsp; 
                                        <?php } ?>


                                    <?php } ?>
                                </ul>
                                <?php if (!empty($this->auth_info)) { ?>
                                    <ul class="nav navbar-nav navbar-right" style="margin-right: 17px;">
                                        <li></li>&nbsp; 
                                        <li><a href="<?= $this->baseUrl() ?>/login/profile"><i class="glyphicon glyphicon-user"></i><?= $this->auth_info->name ?></a></li>&nbsp; 
                                        <li><a href="<?= $this->baseUrl() ?>/login/logout"><i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
                                    </ul>
                                <?php } else { ?>
                                    <ul class="nav navbar-nav navbar-right" style="margin-right: 17px;">
                                        <li></li>&nbsp; 
                                        <li><a href="<?= $this->baseUrl() ?>/login/register"><i class="glyphicon glyphicon-user"></i> Signup</a></li>&nbsp; 
                                        <li><a href="<?= $this->baseUrl() ?>/login"><i class="glyphicon glyphicon-log-out"></i> Login</a></li>&nbsp; 
                                    </ul>
                                <?php } ?>
                            </div>
                        </div>
                    </nav>

                </div>
            </div>
        </header>
        <!--                                    <li class="dropdown">
                                                                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                                                                            <ul class="dropdown-menu">
                                                                                                <li><a href="#">Action</a></li>
                                                                                                <li><a href="#">Another action</a></li>
                                                                                                <li><a href="#">Something else here</a></li>
                                                                                                <li role="separator" class="divider"></li>
                                                                                                <li class="dropdown-header">Nav header</li>
                                                                                                <li><a href="#">Separated link</a></li>
                                                                                                <li><a href="#">One more separated link</a></li>
                                                                                            </ul>
                                                                                        </li>-->